version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/yusuke
    restart: always
    command: bash -c "npm install --only=prod && npm run docker"
    environment:
      - MONGO_URL=mongodb://mongo:27017/yusuke
    volumes:
      - ./dist/:/usr/src/yusuke/dist/
      - ./package.json:/usr/src/yusuke/package.json
    ports:
      - "8080:8080"
    links:
      - mongo